/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetFeedParams,
  PagedResponseIssueFeedDTO,
  ReactionRequest
} from '../../model';





export type reactToIssueResponse200 = {
  data: void
  status: 200
}

export type reactToIssueResponseSuccess = (reactToIssueResponse200) & {
  headers: Headers;
};
;

export type reactToIssueResponse = (reactToIssueResponseSuccess)

export const getReactToIssueUrl = (id: number,) => {




  return `/api/v1/issues/${id}/react`
}

export const reactToIssue = async (id: number,
    reactionRequest: ReactionRequest, options?: RequestInit): Promise<reactToIssueResponse> => {

  const res = await fetch(getReactToIssueUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reactionRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: reactToIssueResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as reactToIssueResponse
}




export const getReactToIssueMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reactToIssue>>, TError,{id: number;data: ReactionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof reactToIssue>>, TError,{id: number;data: ReactionRequest}, TContext> => {

const mutationKey = ['reactToIssue'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reactToIssue>>, {id: number;data: ReactionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  reactToIssue(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReactToIssueMutationResult = NonNullable<Awaited<ReturnType<typeof reactToIssue>>>
    export type ReactToIssueMutationBody = ReactionRequest
    export type ReactToIssueMutationError = unknown

    export const useReactToIssue = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reactToIssue>>, TError,{id: number;data: ReactionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reactToIssue>>,
        TError,
        {id: number;data: ReactionRequest},
        TContext
      > => {
      return useMutation(getReactToIssueMutationOptions(options), queryClient);
    }
    export type getFeedResponse200 = {
  data: PagedResponseIssueFeedDTO
  status: 200
}

export type getFeedResponseSuccess = (getFeedResponse200) & {
  headers: Headers;
};
;

export type getFeedResponse = (getFeedResponseSuccess)

export const getGetFeedUrl = (params?: GetFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/feed?${stringifiedParams}` : `/api/v1/feed`
}

export const getFeed = async (params?: GetFeedParams, options?: RequestInit): Promise<getFeedResponse> => {

  const res = await fetch(getGetFeedUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFeedResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as getFeedResponse
}





export const getGetFeedQueryKey = (params?: GetFeedParams,) => {
    return [
    `/api/v1/feed`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFeedQueryOptions = <TData = Awaited<ReturnType<typeof getFeed>>, TError = unknown>(params?: GetFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeed>>> = ({ signal }) => getFeed(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeedQueryResult = NonNullable<Awaited<ReturnType<typeof getFeed>>>
export type GetFeedQueryError = unknown


export function useGetFeed<TData = Awaited<ReturnType<typeof getFeed>>, TError = unknown>(
 params: undefined |  GetFeedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeed>>,
          TError,
          Awaited<ReturnType<typeof getFeed>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeed<TData = Awaited<ReturnType<typeof getFeed>>, TError = unknown>(
 params?: GetFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeed>>,
          TError,
          Awaited<ReturnType<typeof getFeed>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeed<TData = Awaited<ReturnType<typeof getFeed>>, TError = unknown>(
 params?: GetFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFeed<TData = Awaited<ReturnType<typeof getFeed>>, TError = unknown>(
 params?: GetFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






