spring.application.name=fixMyArea
# 1. Connection URL (Creates the DB if it doesn't exist)
spring.datasource.url=jdbc:mysql://localhost:3306/fix_my_area?createDatabaseIfNotExist=true

# 2. Your MySQL Credentials
spring.datasource.username=root
spring.datasource.password=root

# 3. Hibernate Strategy (Automatically creates tables from your UserProfile class)
spring.jpa.hibernate.ddl-auto=update
