/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthorityJurisdiction,
} from '../models/index';
import {
    AuthorityJurisdictionFromJSON,
    AuthorityJurisdictionToJSON,
} from '../models/index';

export interface Create13Request {
    authorityJurisdiction: AuthorityJurisdiction;
}

export interface Delete13Request {
    id: number;
}

export interface GetById13Request {
    id: number;
}

export interface Update13Request {
    id: number;
    authorityJurisdiction: AuthorityJurisdiction;
}

/**
 * 
 */
export class AuthorityJurisdictionControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for create13 without sending the request
     */
    async create13RequestOpts(requestParameters: Create13Request): Promise<runtime.RequestOpts> {
        if (requestParameters['authorityJurisdiction'] == null) {
            throw new runtime.RequiredError(
                'authorityJurisdiction',
                'Required parameter "authorityJurisdiction" was null or undefined when calling create13().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/authorityjurisdictions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorityJurisdictionToJSON(requestParameters['authorityJurisdiction']),
        };
    }

    /**
     */
    async create13Raw(requestParameters: Create13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthorityJurisdiction>> {
        const requestOptions = await this.create13RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorityJurisdictionFromJSON(jsonValue));
    }

    /**
     */
    async create13(requestParameters: Create13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthorityJurisdiction> {
        const response = await this.create13Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for delete13 without sending the request
     */
    async delete13RequestOpts(requestParameters: Delete13Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete13().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorityjurisdictions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async delete13Raw(requestParameters: Delete13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.delete13RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async delete13(requestParameters: Delete13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.delete13Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAll13 without sending the request
     */
    async getAll13RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorityjurisdictions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAll13Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AuthorityJurisdiction>>> {
        const requestOptions = await this.getAll13RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuthorityJurisdictionFromJSON));
    }

    /**
     */
    async getAll13(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AuthorityJurisdiction>> {
        const response = await this.getAll13Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById13 without sending the request
     */
    async getById13RequestOpts(requestParameters: GetById13Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById13().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorityjurisdictions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getById13Raw(requestParameters: GetById13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthorityJurisdiction>> {
        const requestOptions = await this.getById13RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorityJurisdictionFromJSON(jsonValue));
    }

    /**
     */
    async getById13(requestParameters: GetById13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthorityJurisdiction> {
        const response = await this.getById13Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update13 without sending the request
     */
    async update13RequestOpts(requestParameters: Update13Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update13().'
            );
        }

        if (requestParameters['authorityJurisdiction'] == null) {
            throw new runtime.RequiredError(
                'authorityJurisdiction',
                'Required parameter "authorityJurisdiction" was null or undefined when calling update13().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/authorityjurisdictions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorityJurisdictionToJSON(requestParameters['authorityJurisdiction']),
        };
    }

    /**
     */
    async update13Raw(requestParameters: Update13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthorityJurisdiction>> {
        const requestOptions = await this.update13RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorityJurisdictionFromJSON(jsonValue));
    }

    /**
     */
    async update13(requestParameters: Update13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthorityJurisdiction> {
        const response = await this.update13Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
