/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IssueComment,
  IssueCommentRequest,
} from '../models/index';
import {
    IssueCommentFromJSON,
    IssueCommentToJSON,
    IssueCommentRequestFromJSON,
    IssueCommentRequestToJSON,
} from '../models/index';

export interface Create9Request {
    issueCommentRequest: IssueCommentRequest;
}

export interface Delete9Request {
    id: number;
}

export interface GetById9Request {
    id: number;
}

export interface Update9Request {
    id: number;
    issueComment?: IssueComment;
}

/**
 * 
 */
export class IssueCommentControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for create9 without sending the request
     */
    async create9RequestOpts(requestParameters: Create9Request): Promise<runtime.RequestOpts> {
        if (requestParameters['issueCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'issueCommentRequest',
                'Required parameter "issueCommentRequest" was null or undefined when calling create9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/issuecomments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IssueCommentRequestToJSON(requestParameters['issueCommentRequest']),
        };
    }

    /**
     */
    async create9Raw(requestParameters: Create9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueComment>> {
        const requestOptions = await this.create9RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCommentFromJSON(jsonValue));
    }

    /**
     */
    async create9(requestParameters: Create9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueComment> {
        const response = await this.create9Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for delete9 without sending the request
     */
    async delete9RequestOpts(requestParameters: Delete9Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuecomments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async delete9Raw(requestParameters: Delete9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.delete9RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async delete9(requestParameters: Delete9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.delete9Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAll9 without sending the request
     */
    async getAll9RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuecomments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAll9Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IssueComment>>> {
        const requestOptions = await this.getAll9RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IssueCommentFromJSON));
    }

    /**
     */
    async getAll9(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IssueComment>> {
        const response = await this.getAll9Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById9 without sending the request
     */
    async getById9RequestOpts(requestParameters: GetById9Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuecomments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getById9Raw(requestParameters: GetById9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueComment>> {
        const requestOptions = await this.getById9RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCommentFromJSON(jsonValue));
    }

    /**
     */
    async getById9(requestParameters: GetById9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueComment> {
        const response = await this.getById9Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update9 without sending the request
     */
    async update9RequestOpts(requestParameters: Update9Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/issuecomments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IssueCommentToJSON(requestParameters['issueComment']),
        };
    }

    /**
     */
    async update9Raw(requestParameters: Update9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueComment>> {
        const requestOptions = await this.update9RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCommentFromJSON(jsonValue));
    }

    /**
     */
    async update9(requestParameters: Update9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueComment> {
        const response = await this.update9Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
