/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IssueStatusHistory,
} from '../models/index';
import {
    IssueStatusHistoryFromJSON,
    IssueStatusHistoryToJSON,
} from '../models/index';

export interface Create7Request {
    issueStatusHistory: IssueStatusHistory;
}

export interface Delete7Request {
    id: number;
}

export interface GetById7Request {
    id: number;
}

export interface Update7Request {
    id: number;
    issueStatusHistory: IssueStatusHistory;
}

/**
 * 
 */
export class IssueStatusHistoryControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for create7 without sending the request
     */
    async create7RequestOpts(requestParameters: Create7Request): Promise<runtime.RequestOpts> {
        if (requestParameters['issueStatusHistory'] == null) {
            throw new runtime.RequiredError(
                'issueStatusHistory',
                'Required parameter "issueStatusHistory" was null or undefined when calling create7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/issuestatushistorys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IssueStatusHistoryToJSON(requestParameters['issueStatusHistory']),
        };
    }

    /**
     */
    async create7Raw(requestParameters: Create7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueStatusHistory>> {
        const requestOptions = await this.create7RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueStatusHistoryFromJSON(jsonValue));
    }

    /**
     */
    async create7(requestParameters: Create7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueStatusHistory> {
        const response = await this.create7Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for delete7 without sending the request
     */
    async delete7RequestOpts(requestParameters: Delete7Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuestatushistorys/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async delete7Raw(requestParameters: Delete7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.delete7RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async delete7(requestParameters: Delete7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.delete7Raw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAll7 without sending the request
     */
    async getAll7RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuestatushistorys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAll7Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IssueStatusHistory>>> {
        const requestOptions = await this.getAll7RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IssueStatusHistoryFromJSON));
    }

    /**
     */
    async getAll7(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IssueStatusHistory>> {
        const response = await this.getAll7Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById7 without sending the request
     */
    async getById7RequestOpts(requestParameters: GetById7Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/issuestatushistorys/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getById7Raw(requestParameters: GetById7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueStatusHistory>> {
        const requestOptions = await this.getById7RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueStatusHistoryFromJSON(jsonValue));
    }

    /**
     */
    async getById7(requestParameters: GetById7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueStatusHistory> {
        const response = await this.getById7Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update7 without sending the request
     */
    async update7RequestOpts(requestParameters: Update7Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update7().'
            );
        }

        if (requestParameters['issueStatusHistory'] == null) {
            throw new runtime.RequiredError(
                'issueStatusHistory',
                'Required parameter "issueStatusHistory" was null or undefined when calling update7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/issuestatushistorys/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IssueStatusHistoryToJSON(requestParameters['issueStatusHistory']),
        };
    }

    /**
     */
    async update7Raw(requestParameters: Update7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueStatusHistory>> {
        const requestOptions = await this.update7RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueStatusHistoryFromJSON(jsonValue));
    }

    /**
     */
    async update7(requestParameters: Update7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueStatusHistory> {
        const response = await this.update7Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
