name: 🛠 Task
description: Technical or development task
title: "[TASK]: "
labels: ["task"]

body:
  - type: textarea
    id: task
    attributes:
      label: 📝 Task Description
      placeholder: Describe the task clearly
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority
      options:
        - Low
        - Medium
        - High

  - type: textarea
    id: notes
    attributes:
      label: 📌 Additional Notes
