/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueVoteRequest
 */
export interface IssueVoteRequest {
    /**
     * 
     * @type {number}
     * @memberof IssueVoteRequest
     */
    issueId?: number;
    /**
     * 
     * @type {number}
     * @memberof IssueVoteRequest
     */
    userProfileId?: number;
}

/**
 * Check if a given object implements the IssueVoteRequest interface.
 */
export function instanceOfIssueVoteRequest(value: object): value is IssueVoteRequest {
    return true;
}

export function IssueVoteRequestFromJSON(json: any): IssueVoteRequest {
    return IssueVoteRequestFromJSONTyped(json, false);
}

export function IssueVoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueVoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'issueId': json['issueId'] == null ? undefined : json['issueId'],
        'userProfileId': json['userProfileId'] == null ? undefined : json['userProfileId'],
    };
}

export function IssueVoteRequestToJSON(json: any): IssueVoteRequest {
    return IssueVoteRequestToJSONTyped(json, false);
}

export function IssueVoteRequestToJSONTyped(value?: IssueVoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issueId': value['issueId'],
        'userProfileId': value['userProfileId'],
    };
}

