/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueCommentRequest
 */
export interface IssueCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof IssueCommentRequest
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssueCommentRequest
     */
    isFromAuthority?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssueCommentRequest
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IssueCommentRequest
     */
    issueId?: number;
    /**
     * 
     * @type {number}
     * @memberof IssueCommentRequest
     */
    userProfileId?: number;
}

/**
 * Check if a given object implements the IssueCommentRequest interface.
 */
export function instanceOfIssueCommentRequest(value: object): value is IssueCommentRequest {
    return true;
}

export function IssueCommentRequestFromJSON(json: any): IssueCommentRequest {
    return IssueCommentRequestFromJSONTyped(json, false);
}

export function IssueCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'isFromAuthority': json['isFromAuthority'] == null ? undefined : json['isFromAuthority'],
        'isDeleted': json['isDeleted'] == null ? undefined : json['isDeleted'],
        'issueId': json['issueId'] == null ? undefined : json['issueId'],
        'userProfileId': json['userProfileId'] == null ? undefined : json['userProfileId'],
    };
}

export function IssueCommentRequestToJSON(json: any): IssueCommentRequest {
    return IssueCommentRequestToJSONTyped(json, false);
}

export function IssueCommentRequestToJSONTyped(value?: IssueCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'isFromAuthority': value['isFromAuthority'],
        'isDeleted': value['isDeleted'],
        'issueId': value['issueId'],
        'userProfileId': value['userProfileId'],
    };
}

