/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface State
 */
export interface State {
    /**
     * 
     * @type {number}
     * @memberof State
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof State
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof State
     */
    code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof State
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof State
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    version?: number;
}

/**
 * Check if a given object implements the State interface.
 */
export function instanceOfState(value: object): value is State {
    return true;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function StateToJSON(json: any): State {
    return StateToJSONTyped(json, false);
}

export function StateToJSONTyped(value?: State | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': value['version'],
    };
}

