package com.diviso.fix_my_area.enumeration;

public enum AuthorityRole {
    WARD_PRESIDENT, PANCHAYATH_PRESIDENT, BLOCK_PANCHAYATH_PRESIDENT, DISTRICT_PANCHAYATH_PRESIDENT, MLA, MP, MINISTER, CHIEF_MINISTER, COLLECTOR, ADDITIONAL_COLLECTOR, IPS_OFFICER, DISTRICT_SP, CIRCLE_INSPECTOR, POLICE_INSPECTOR, SUB_INSPECTOR, CIVIL_SERVANT, DISTRICT_MEDICAL_OFFICER, HEALTH_OFFICER, REVENUE_OFFICER, TAHSILDAR, VILLAGE_OFFICER, JUDGE, MAGISTRATE, MUNICIPAL_COMMISSIONER, CORPORATION_SECRETARY, OTHER
}
