spring.application.name=fix_my_area

spring.datasource.url=jdbc:mysql://localhost:3306/fix_my_area?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.clean-on-validation-error=true
spring.flyway.out-of-order=true

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7585df54b73fb46e15d8628b76fb0d2
jwt.expiration=86400000
