/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetFeedParams = {
filter?: string;
wardId?: number;
lat?: number;
lng?: number;
page?: number;
size?: number;
};
