/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IssueStats } from './issueStats';

export interface IssueFeedDTO {
  id?: number;
  title?: string;
  tag?: string;
  status?: string;
  image?: string;
  distance?: string;
  time?: string;
  authority?: string;
  stats?: IssueStats;
}
