/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IssueFeedDTO } from './issueFeedDTO';
import type { PageableInfo } from './pageableInfo';

export interface PagedResponseIssueFeedDTO {
  content?: IssueFeedDTO[];
  pageable?: PageableInfo;
  last?: boolean;
  totalPages?: number;
  totalElements?: number;
}
